### PR TITLE
New feature that renders the spinner component based on it parent element

### PR DESCRIPTION
**Pull request by tomurlh**
A functionality that show the spinner component just inside it's parent element. It's good to use it with ajax requests, when the user have to wait for the response.
This feature does not block the whole page or form, just the components and it parent that makes the request.

**Configuration**
The configuration it's pretty simple, just:
- pass the `:inside-parent` prop to the spinner component, that receives a boolean
- add/change the `position: relative` css attribute to the parent element or component of the spinner

A example of how it works it's already implemented in the examples page of this pull request.

### CODE REVIEW

**Comment by tomurlh** [comment]
@dzwillia you can review this and consider the improvements to make. A example of this feature is [here](https://giphy.com/gifs/103tfTZOqMIfTi/fullscreen).

**Comment by tomurlh** [comment]
@dzwillia Waiting for an answer anxiously.

**Comment by dzwillia** [comment]
Thanks for your interest in **vue-simple-spinner**!

I can't merge this pull request as-is. The changes suggested are too far-reaching and can already be achieved easily enough:

* Conditionally showing the spinner can easily be achieved using the `v-if` or `v-show` directives with some data properties (for use with your AJAX calls).
* Rendering the spinner in a parent is already supported (in fact all of the spinners in the examples app are rendered in their respective parents). If you want to gray out the form or other elements behind the spinner, this can be achieved easily enough with just a little bit of CSS.

**Comment by tomurlh** [comment]
Thanks for answering.
If I'm not wrong, the spinner is rendered in their parents, but not at the center of it (horizontally and vertically) and above of it, like blocking the whole parent element (until the AJAX calls ends). About the gray color it's just for indicating that something it's being executed. In deed this is reachable with some CSS, but the changes automates passing a boolean prop to the spinner.

**Comment by dzwillia** [comment]
I've updated the examples in v1.2.3 to show how to position the spinner inside a parent element wherever desired.

In general, in trying to keep with the "simple" part of the spinner, I've opted not to include options for changing the positioning of the spinner inside a parent since this can be achieved easily enough by changing the style of the parent element.

Hope the new layout examples are helpful to you!

**Comment by ReynerHL** [comment]
It is not clear for me how to position the spinner inside a parent element.

Reading the examples I can't find for instance where are the definitions for the classess "mb5 center". Are we have to use an specific css framework that have those class already defined? Could this awesome feature be treated as a component props instead ?

Something like:
```html
<spinner :pos="v-middle h-center"></spinner>

**Comment by tomurlh** [comment]
@ReynerHL to use the code from this pull request you have to download the code from [this](https://github.com/tomurlh/vue-simple-spinner) and to render spinner in the parent element only, pass the :inside-parent prop to spinner:
`<spinner :pos="v-middle h-center"></spinner>`
and change the parent css style position to relative:
`position: relative`

But when I'm developing it, @dzwillia was developing too and has released an update with it in the original [repo](https://github.com/dzwillia/vue-simple-spinner). Because of it this pull request was closed :sweat_smile:

**Comment by ReynerHL** [comment]
@tomurlh Thanks for your concern. I was reading the @dzwillia comment and I just thought that searching in its example_src folder we will find how to get the same "centered from its parent element" feature.

Can you @tomurlh please explain how we can target your repo in order to test this? It seems like the default npm registry points to this repo instead. We are using "yarn" here.

Thanks in advance.

**Comment by dzwillia** [comment]
@ReynerHL The spinner element is intentionally left without any CSS positioning style which allows the parent element it is used in to determine how it is positioned. In the examples source, I am using the excellent [Tachyons CSS micro-framework](http://tachyons.io/). In most cases, it basically maps 1 CSS style to a CSS class: `.dib` == `display: inline-block`, `.tr` == `text-align: right`, etc.

The spinner is a block element by default, but this can be changed by adding either a CSS style or class like so: `<spinner style="display: inline-block"></spinner>`. Since I'm using Tachyons in the examples app, I simply do the following: `<spinner class="dib"></spinner>`.

If you just want to align the spinner horizontally, you can use text alignment on the parent element and make the spinner `inline-block`. The following code snippet will align the spinner on the right side of its parent element:

```html
<div style="text-align: right">
  <spinner style="display: inline-block"></spinner>
</div>
```

If you want to center the spinner vertically in a parent element, the easiest way is to use [flexbox CSS](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) on the parent element. The following code snippet will vertically and horizontally center the spinner in its parent element:

```html
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100px">
  <spinner></spinner>
</div>
```

If you'd like to play around with the spinner component, here's a [JsFiddle](http://jsfiddle.net/dzwillia/kc5ka8zu/) I've set up for these purposes.

Hope this is helpful to all of you!

**Pull request closed without merging**
